version: "3.3"
name: mega-backuper

services:
  mega-backuper:
    image: jsfraz/mega-backuper
    container_name: mega-backuper
    restart: always
    volumes:
      - temp:/app/temp
      # - ./mega-backuper.json:/app/mega-backuper.json

volumes:
  temp: